# Generated by Django 6.0.3 on 2026-05-05 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0039_module_question_order_high_water'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('subject', models.CharField(blank=True, db_index=True, help_text='Optional subject tag (e.g. MATH, READING_WRITING).', max_length=32, null=True)),
            ],
            options={
                'db_table': 'question_categories',
            },
        ),
        migrations.CreateModel(
            name='ModuleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'db_table': 'module_questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RenameIndex(
            model_name='attemptengineaudit',
            new_name='exams_attem_attempt_8fe07f_idx',
            old_name='exams_audit_att_cre',
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='abandoned_checkpoint_state',
            field=models.CharField(blank=True, default='', help_text='Snapshot of current_state persisted when transitioning to ABANDONED (authoritative resume target; empty/null => restart module 1).', max_length=24, null=True),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'subject'), name='uniq_category_name_subject'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='exams.category'),
        ),
        migrations.AddField(
            model_name='modulequestion',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_questions', to='exams.module'),
        ),
        migrations.AddField(
            model_name='modulequestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_questions', to='exams.question'),
        ),
        migrations.AddConstraint(
            model_name='modulequestion',
            constraint=models.UniqueConstraint(fields=('module', 'order'), name='uniq_modulequestion_order_per_module'),
        ),
        migrations.AddConstraint(
            model_name='modulequestion',
            constraint=models.UniqueConstraint(fields=('module', 'question'), name='uniq_modulequestion_per_module'),
        ),
    ]
