# Generated by Django 6.0.3 on 2026-05-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0041_backfill_modulequestion_from_question_module'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='question',
            name='uniq_question_order_per_module',
        ),
        migrations.RemoveField(
            model_name='question',
            name='module',
        ),
    ]
