# Generated by Django 6.0.3 on 2026-05-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0042_remove_question_uniq_question_order_per_module_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
