# Generated by Django 6.0.3 on 2026-04-26 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_refresh_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(db_index=True, default='info', max_length=16)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'users_security_audit_events',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='users_teacher_admin_subject_required',
        ),
        migrations.RenameIndex(
            model_name='refreshsession',
            new_name='users_refre_user_id_882fe0_idx',
            old_name='users_refr_user_id_6c2b1f_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='last_password_change',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when the user changes password via API (adaptive security).', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='security_step_up_required_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='scope',
            field=models.JSONField(blank=True, default=list, help_text='Legacy field; not used for authorization. Use ``User.subject`` and ``access.UserAccess``.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subject',
            field=models.CharField(blank=True, choices=[('math', 'Math'), ('english', 'English')], db_index=True, help_text='Required for **teacher** (math or english). Must be null for admin, test_admin, super_admin, and students.', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='securityauditevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='securityauditevent',
            index=models.Index(fields=['user', '-created_at'], name='users_secur_user_id_13bd0b_idx'),
        ),
    ]
